### ISSUE TITLE
Does not work on OS X

### ISSUE THREAD

**Issue by junegunn** [D630/fzf-fs#1]
This is a very interesting application of fzf.

I noticed that the script fails on OS X because `find` there does not have `-printf` option. Replacing `-printf '%f\n'` with `basename` will probably solve the issue. It's up to you though to decide whether to fix it for OS X or not.

And due to the recent [change in `+s` option](http://junegunn.kr/2015/03/fzf-0.9.4/), you might want to put `--tac` option for fzf 0.9.4 and above.

**Comment by D630** [comment]
Ja, the `-printf` primary is only implemented in `GNU find`, not `BSD find`. I will fix the relevant function in the script.

**Comment by D630** [comment]
Ok, I wrote [115eb8a](https://github.com/D630/fzf-fs/commit/115eb8a0eed92e97a73fa265d2946c8f8dc08ef3). How is it working out now?

**Comment by D630** [comment]
ps: a very interesting page about `find` is http://www.in-ulm.de/~mascheck/various/find/

**Comment by D630** [comment]
Hey, I pushed some commits to the develop branch. Could you try it out and see, whether it works on OS X?

**Comment by junegunn** [comment]
Works!

**Comment by junegunn** [comment]
![ansi](https://cloud.githubusercontent.com/assets/700826/6749227/77768a00-cf31-11e4-8985-387b2c0675d5.png)

Screenshot with new `--ansi` option :)
I'm planning to release 0.9.5 in a week or two. I'll let you know when it's ready.

**Comment by D630** [comment]
Cool!

**Comment by junegunn** [comment]
I just merged the changes to the master branch and released 0.9.5 binary with `--ansi` option. For example, `tree -C | fzf --ansi --reverse` will give nice colored tree inside fzf.

I think your project will benefit from the addition of this option. You'll have to force `ls` to still use ANSI colors even when its output is redirected. `CLICOLOR_FORCE=1 ls` on OS X (or BSD), `ls --color=always` on Linux.

**Comment by D630** [comment]
Super cool! I will implement it in the next days. Thanks! :)

**Comment by junegunn** [comment]
Cool, you might also want to check out the new `--expect` option of 0.9.6 that I just released. It'll allow you to define some basic key mappings.

**Comment by D630** [comment]
All right. I have implemented colour support via `fzf --ansi`.

Because parsing coloured ls output is a bit tricky, I have worked around it with `paste` and `mkfifo` (in `mksh` there is no process substitution yet). That's why it's a bit slow. On FreeBSD versions the ls command is `CLICOLOR_FORCE=1 ls -G`; it is preconfigured with `fzf-fs-init` and later configurable via `FZF_FS_LS_COMMAND_COLOR`.

Feel free to test the develop branch. After cloning, configure `FZF_FS_CONFIG_DIR` and run `fzf-fs --init`. Colour is on per default :smile:

**Comment by junegunn** [comment]
Thanks! I suppose you meant the `develop` branch. It works as expected on Linux, but unfortunately I see errors on OS X (`fzf-fs: line 403: CLICOLOR_FORCE=1: command not found`) even after I deleted ~/.config/fzf-fs.d and reinitialized.

While trying out fzf-fs, I realized that it would be better if we could fine-tune the sort criteria of fzf. I'll probably add an option for that in the next release.

**Comment by D630** [comment]
Ok. I have modified `__fzffs_ls` and `__fzffs_ls_color` with b30e0ac2af.  That should fix `fzf-fs: line 403: CLICOLOR_FORCE=1: command not found`

**Comment by junegunn** [comment]
Ah, yes, now it works. Thanks!
I'd like to let you know that I just released fzf 0.9.9 with new `--tiebreak` and `--no-hscroll` options. Check it out if you're interested.

```
       --tiebreak=STR
              Sort criterion to use when the scores are tied

              length  Prefers item with shorter length
              begin   Prefers item with matched substring closer to the beginning
              end     Prefers item with matched substring closer to the end
              index   Prefers item that appeared earlier in the input stream
```

**Comment by D630** [comment]
Thanks :)

**Comment by D630** [comment]
It's been a long time, but fzf-fs works now with `bind` and `expect`:)

Feel free to test [it](https://github.com/D630/fzf-fs/tree/0.2.3/README.md)!

```
git clone -b 0.2.3 --single-branch --depth 1 --recursive -- https://github.com/d630/fzf-fs
```
