### ISSUE TITLE
fzf-fs doesn't support newlines in filenames

### ISSUE THREAD

**Issue by evverx** [D630/fzf-fs#11]
Hi!

```shell
cd
# install fzf-fs
git clone https://github.com/D630/fzf-fs
PATH=$PATH:~/fzf-fs
fzf-fs --init

# make test directory
mkdir -p test
mkdir -p test/$'a\nb'
mkdir -p test/$'a\nb\nc'

# run fzf-fs
source fzf-fs/fzf-fs test
```

Incorrect view:
![screen shot 2015-07-05 at 18 01 16](https://cloud.githubusercontent.com/assets/10195800/8512175/e520a678-233f-11e5-9ca0-c6b0c4e18943.png)

`cd` doesn't work.

**Comment by evverx** [comment]
Fixed
You should see something like this:
![screen shot 2015-07-05 at 21 45 31](https://cloud.githubusercontent.com/assets/10195800/8512883/3ab8c740-235f-11e5-8a8b-32768e26edc8.png)

**Comment by D630** [comment]
Merci! :smile:

Unfortunately, there is still this new line bug when opening files via the "console commands". I will work around this in version 0.3.0., #13

**Comment by evverx** [comment]
I don't use "console commands":)
I use `fzf-fs` as an interactive `cd`: http://unix.stackexchange.com/a/214001/120177 :)
Thanks!

**Comment by D630** [comment]
Ok. I see :smiley: 

Version 0.3 will be muuuch better ....
